server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always


spring:
  application:
    name: servicioProducto
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: 12345
  boot:
    admin:
      client:
        url: http://localhost:8086
